defaults: &defaults
  :log_level: info
  :mongo:
    :database: davis
    :host: localhost
  :domain: verlag.dev 
  :images:                    
    :large: [640, 640, false] 
    :display: [640, 480, false]
    :thumbnails: [120, 120, false]
    :icons: [72, 72, true]

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults
  :mongo:
    :database: davis_test
    :host: localhost

:production:
  <<: *defaults
